services:
  db:
    image: mysql:8
    container_name: capstone-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bootcamp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: capstone-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CLIENT_ORIGIN: http://localhost:3000

      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: bootcamp
      DB_USER: root
      DB_PASSWORD: root123

      JWT_SECRET: myAccessSecret123
      REFRESH_SECRET: myRefreshSecret456

    depends_on:
      - db

volumes:
  mysql_data: